### ISSUE TITLE
cant  login with QRcode , i try use  login via otp , success login for 1 account telegram , but when i try to make login for second accound , otp cant run.

### ISSUE THREAD

**Issue by sundulgan** [thebrumby/HotWalletClaimer#12]
![image](https://github.com/thebrumby/HotWalletClaimer/assets/89188633/b5e20bd3-2150-4356-b1eb-ea6ff44ec623)

**Comment by sundulgan** [comment]
![image](https://github.com/thebrumby/HotWalletClaimer/assets/89188633/d1f595e0-5f36-4c1b-89da-f6c176f29c1e)

error while using QR to login tele

**Comment by Wellynounet** [comment]
Hello, 


Are you to to date ?  if not  do this in in the HotWalletBot
git pull 



Can you rerun ./install.sh and let me know if there are any errors?

How did you manage the other accounts?



Can you tell me more about the versions you're using? Your OS, the version of your ChromeDriver, and your Chrome or Chromium browser?

Run the following commands:
lsb_release -a
chromedriver --version
chromium --version

**Comment by thebrumby** [comment]
Hi, 

The second screenshot tells us it could see no QR code to interact with, and the first screenshot did not find the element identified by //div[@class='input-field-input']//span[@class='i18n']. However, I just checked on Telegram and this is still the correct XPath.

I wonder if you have some kind of firewall setting that it is blocking access to Telegram? I notice you already have the debug setting on - so if you navigate to the folder "screenshots" and in your example "BNB-Cold:cold_3166" you should see some jpegs like this:

Step 01 - Initial QR code.png
![Step 01 - Initial QR code](https://github.com/thebrumby/HotWalletClaimer/assets/29182343/d2c22f8e-4826-4501-8042-3eb56a94d9d3)

02-switch to log in by phone number.png
<img width="234" alt="02-switch to log in by phone number" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/a62e84c9-2245-4368-857d-47c6ce055d83">


03-update users country.png
<img width="188" alt="03-update users country" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/aac89ec0-25b9-4a91-ae16-44cc36f6e308">

Unless of course, something is blocking Chromedriver from getting that information.

**Comment by thebrumby** [comment]
One final thought, and at the risk of making assumptions, there is a possibility that you are not seeing the login screen because you previously logged in correctly, but that it didn't finalize the setup somehow. 

If you see a screen like this:
<img width="243" alt="03-app-opened" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/3a344324-79ab-42dd-878c-87dfa65f48a4">

then please check your folder `selenium/BNB-Cold:cold_3166` it should have a file called `cookies.json` in that folder. If it's missing (because the installer crashed before the end maybe. You can just create an empty file named `cookies.json` and when you run it in PM2 or the command-line, it will recognize that it's an existing session and start to claim.

**Comment by sundulgan** [comment]
![image](https://github.com/thebrumby/HotWalletClaimer/assets/89188633/e178db38-c744-4729-8667-e524386c842b)

Why is it that after pressing the next button the storage_offline button appears? i think this is problem in otp

**Comment by thebrumby** [comment]
Hi, 

So the issue is your telegram account is not working - after entering the Country Code and Phone number, you're getting blocked from making a new login by the "Storage Offline" message.

You'll have to resolve to be able to log in via web.telegram.org before the script will work. 

When I was testing I hit this message quite a lot (repeatedly login in when it was limited to 20 tries per day. Once this is resolved we can try again :)

**Comment by thebrumby** [comment]
Once the issue is cleared and you are able to log in again, after logging in, you can save the Telegram session, so you'll only need to authenticate the once :)

**Comment by sundulgan** [comment]
oke thank u mate , btw u have code to  automate airdrop tap tap or click click system like notcoin? which can directly hit the api endpoint?

**Comment by thebrumby** [comment]
Hi Sundulgan, 

Telegram changed some of their log in XPATHs, which I have corrected and uploaded - but I found an interesting fact!

Reusing a previous wallet name for a Telegram Login gave me a "STORAGE_OFFLINE" error, even though I can log in with Telegram Web. However, if I start a "virgin" session, it works just fine. I added extra checks in the script to output this to the console. But potentially, if you run the commands below, you might just find it works!:

```
rm -rf selenium/BNB-Cold:cold_3166
./launch.sh cold BNB-Cold:cold_3166
```
