### ISSUE TITLE
Cant login into telegram

### ISSUE THREAD

**Issue by ryandhikacc** [thebrumby/HotWalletClaimer#14]
whenever i tried to login, script just goes like this, no qrcode, no otp, no whatsoever related to telegram login, what am i missing? i'm using docker
![image](https://github.com/thebrumby/HotWalletClaimer/assets/159438475/335b69f4-5e66-4c92-b0c0-0108231f3af2)

**Comment by thebrumby** [comment]
Hi, 

Please can you follow the steps in this post:

https://github.com/thebrumby/HotWalletClaimer/issues/12

It will require you to change the settings and set the debugIsOn to "y" (yes). Then kindly follow the instructions to check the screenshots by attempting to log in again - from there we can see if the account is locked out (for new logins) or some other issue. 

Thank you.

**Comment by ryandhikacc** [comment]
Hi, thanks for the response, I'm using docker and I can't seem to find the locally saved screenshots folder, where is it?

**Comment by Wellynounet** [comment]
![image](https://github.com/thebrumby/HotWalletClaimer/assets/88185485/64ae2c50-02ca-418a-9f79-4f49e111d4f7)


here

**Comment by ryandhikacc** [comment]
somehow qrcode is visible here in debug screenshots
![image](https://github.com/thebrumby/HotWalletClaimer/assets/159438475/4af5580a-5465-4cb1-8914-17fffa550c4e)
but here the logs:
CHROME DRIVER INITIALISED: Try not to exit the script before it detaches.
Step 01 - QR Code is no longer visible.
Step 02 - Attempting to check for 2FA requirement (will timeout if you don't have 2FA)...
Step 02 - 2FA input field not found.

**Comment by thebrumby** [comment]
OK - I wonder if the page is slow loading? How would you rate your internet connection?

If possible, could you be able to look for this line around line 357, inside the def log_into_telegram() function:

`wait = WebDriverWait(driver, 5)`

and change it to 

`wait = WebDriverWait(driver, 15)`
        
 It will slow the log in process down, but might make it work better. If it works I'll have to consider if I change it with the main routine.

**Comment by ryandhikacc** [comment]
I am using a vps and speedtest shows 1gbps, I think speed is not the issue here, but adding a 15 second wait time instead of 5 seconds would be better and would accommodate people who have slightly slow internet

**Comment by thebrumby** [comment]
Hi, 

Thanks for the info. You're right, it would appear in your case that connection speed isn't the issue. I made a tweak to the 3 games that use TG login, to ensure the first QR code is present before then monitoring if it disappears. 

It should avoid the situation when the QR code is perceived by the script to have disappeared, before it even appeared for the first time. 

I hope it also solves your issue, please let me know.

**Comment by ryandhikacc** [comment]
I've finished updating the script, and now that it's good, the QR code now appears
![image](https://github.com/thebrumby/HotWalletClaimer/assets/159438475/9404a1e6-ffcd-4355-953e-45d3fce72c29)
but the problem is that my account has 2fa enabled and after entering 2fa correctly it appears error as above, here is the debug screenshot:
![image](https://github.com/thebrumby/HotWalletClaimer/assets/159438475/e66d0acc-e81d-4b19-8a11-e6b2c353250a)

**Comment by ryandhikacc** [comment]
ok, so apparently problem is exactly same as #12 , there is missing cookies,json in my folder, i added it using `touch cookies.json` but then you said :

> when you run it in PM2 or the command-line, it will recognize that it's an existing session and start to claim.

what pm2 command are you referring to?

**Comment by thebrumby** [comment]
Hi! 

Telegram has given me a busy few hours today as they changed some of the XPATHs that the script identifies to interact with the browser on the user's behalf!

As it turns out, maybe the error you were seeing was kind of genuine, and the cookies didn't get set because it hadn't finished the sequence.

In any case, I pushed an update for the games that require a TG login to the repository and in my various test environments it's working well. 

After pulling the latest copies of the script, it's probably best if you start the process again by deleting your current session `rm -rf selenium/Wave:Wallet1` or whatever you named it. You can then launch it again with `./launch.sh wave Wave:Wallet1` or the previous way and see how you get on :)

If all works well, after getting through the TG login and 2FA authentication, you can save that TG session (if you choose) and use it with one or more wave accounts (just restore the existing TG session and add another seed phrase) or use the TG sessions for any of the other games if you like.

Please let me know how you get on.
