### ISSUE TITLE
Error with updating catalog and error with sessions

### ISSUE THREAD

**Issue by VanyaOnegin** [thebrumby/HotWalletClaimer#146]
Hi, I have a couple of questions about Hot Wallet. If it's not difficult for you, please answer. The first question is: what should I do if all sessions work perfectly for a week, and then they turn off and stop working? The second question is: how can I update my HotWalletBot directory if I installed it according to your Stand-alone Linux Installation guide (https://github.com/thebrumby/HotWalletClaimer/blob/main/docs/LINUX.md ). I mean, I installed it 2 weeks ago and during that time you updated it, how do I change my files to the updated ones without touching the session, that is, so that I don't have to re-upload my telegram accounts to the program. Thank you in advance, I really hope for your help.

**Comment by thebrumby** [comment]
Hi,

To determine why it stopped working, you would need to enable the debugging screenshots in the options configuration. Please be aware that the game itself was experiencing issues yesterday, such as people not being able to log in. While this may or may not be the root cause, obviously on occasions where the human being can not log in, the script can not log in either :) After restarting one or more game sessions with debugging enabled, you can check inside the screenshots folder and then the subfolder for your game sessions.

Regarding updating, GitHub has this command for updating:

```
git pull
```

You need to be inside the HotWalletBot directory when you run it, and it will update any project files, without affecting your saved game sessions.

Thanks

**Comment by VanyaOnegin** [comment]
Thank you so much
