### ISSUE TITLE
Developing Documentation

### ISSUE THREAD

**Issue by rostamzad1900** [thebrumby/HotWalletClaimer#169]
hey phil
i'm currently develop two game (**_Cedex_** , **_WigWam_**) and worked perfectly fine.
i'm look into other games code like _**Seed**_ and  copy the idea to develop these games.

as you know there is been many ways you can open games that won't open in **_web.telegram.org_**.
for example hamster kombat won't open in desktop browser, but if you use **_Resource Override_** technique like [this](https://serezhka.github.io/posts/hamsterkombat-clicker/)  you can open and use in browser

if there is any kind of material that we can use and develop other games, it would be soo helpful
because these code configure to run in pm2, don't open any browser that we can see visual procedure to debugging.

**Comment by thebrumby** [comment]
Hi,

What happens if you force it to use the built-in proxy?

```
    def initialize_settings(self):
        super().initialize_settings()
        self.forceLocalProxy = True
```

**Comment by thebrumby** [comment]
I map the game paths in Desktop Chrome by the way.

**Comment by rostamzad1900** [comment]
> Hi,
> 
> What happens if you force it to use the built-in proxy?
> 
> ```
>     def initialize_settings(self):
>         super().initialize_settings()
>         self.forceLocalProxy = True
> ```

it's not working with proxy enabled

![image](https://github.com/user-attachments/assets/bd0c5159-54c4-4c7c-9e8c-4b42d1aa0869)

**Comment by thebrumby** [comment]
Hi,

Most of the games featured here work with Telegram Web. Due to a high number of requests for games where Telegram Web was blocked, we added the proxy to attempt to rewrite the Telegram platform during the live traffic. This method is the same thing you mentioned for Hamster Kombat.

Additionally JBR used this in one of his game commits:

```
    def launch_iframe(self):
        super().launch_iframe()

        # Open tab in main window
        self.driver.switch_to.default_content()

        iframe = self.driver.find_element(By.TAG_NAME, "iframe")
        iframe_url = iframe.get_attribute("src")
        iframe_url = iframe_url.replace("tgWebAppPlatform=web", "tgWebAppPlatform=android")

        self.driver.execute_script("location.href = '" + iframe_url + "'")
```
        
Ultimately this project was intended to provide a framework for using a genuine browser session with simulated mouse movements and clicks to autoclaim these crypto games, but in the most human-like way possible. When game developers use a significant number of methods to block TG Web access, it's not something that I'm actively looking to overcome.
