### ISSUE TITLE
SimpleTap Issue-No evidence you followed the troubleshooting guide so it is closed.- "The issue with the game wasn't resolved, it keeps spamming an endless number of lines every second." You can easely close this issue too .............

### ISSUE THREAD

**Issue by Imaroubat** [thebrumby/HotWalletClaimer#178]

**Comment by thebrumby** [comment]
SImpleTap works fine for me, and fine for our tester in France. If you followed the troubleshooting steps, you might see from the screenshots what the problem is, or at least be able to share them here so we could have helped you.

Not following the forum rules wastes everyone's time, when people wonder why there is no new games, the answer is because I spent 2 hours a day checking out things that work fine for me. This thread will be closed and locked.

**Comment by thebrumby** [comment]
<img width="956" alt="image" src="https://github.com/user-attachments/assets/f75a7406-e891-4226-ada6-f0cc0f1f6e0b">
