### ISSUE TITLE
Help Me: with iframe switching

### ISSUE THREAD

**Issue by Jelingam** [thebrumby/HotWalletClaimer#216]
hey @thebrumby 
i'm developing some feature and i'm wonder why in some game switching to iframe works and on another don't
in `claimer.py` we have a function that extract iframe source link, and the code switchs to this new link.
but in some games this not will happen.
for example seed game.

the code is perfectly fine. but with this feature i need to open iframe completely in a new tab.

![01](https://github.com/user-attachments/assets/fb556cac-476e-40d4-b090-27db2ee45d08)

**Comment by thebrumby** [comment]
Hi @Jelingam,

I’m not entirely sure I understand your question, could you explain further?

In the new pop-up modal in the "k" version of Telegram, the iFrame containing the game extends from the bottom of the tab for switching games to the bottom of the modal. In my `claimer.py`, every script calls the `launch_iframe()` function, as every game is in an iFrame. The default div that contains the iFrame is "web-app-body", and by directing Selenium/Chromedriver to switch to it, we can interact with the game content:

<img width="1015" alt="image" src="https://github.com/user-attachments/assets/5f7cae72-5091-4248-89e8-796315127ad4">

<br><br>
> we have a function that extract iframe source link, and the code switchs to this new link.
but in some games this not will happen.

Again, I'm not sure what you mean by this. As you can see in my screenshot above, the main contents of the modal are loaded as an iFrame, in this example, from "https://tgapp.herewallet.app". 

<img width="602" alt="image" src="https://github.com/user-attachments/assets/9df05d56-b3c5-4dd9-bf2d-eb6f7b16792a">


In every game, you should see the steps above (depending on your verbose settings). The screenshot above shows the console log reporting that it was able to successfully switch to the iFrame using the code below:

```python
container = wait.until(EC.presence_of_element_located((By.CLASS_NAME, iframe_container_class)))
iframe = container.find_element(By.TAG_NAME, "iframe")
self.driver.switch_to.frame(iframe)
```

If the script was not able to switch to the iFrame, then it wouldn’t be able to obtain the token balance, the time until the pot filled, or be able to click any of the links, such as claiming any available tokens. Selenium can only interact with these elements if you explicitly switch to the iFrame. 

Maybe you are getting confused by the screenshots from Chromedriver? They show the iFrame as represented in the virtual browser, but as I deliberately set the browser window higher and wider than the game iFrame, you can also see the Telegram chat in the background. Without these extra dimensions, you might not see clearly if something is blocking your session. This is separate from the fact that Selenium is interacting with content solely within the iFrame.

You mention that you're developing some offshoot code that loads content into a new iFrame, I'm not really sure why you'd want to do this, however, I guess you’ll have to use some unique identifier that would allow the iFrame to be identified, and then switch to it. You may also need to ensure that the iFrame is fully loaded before switching, using an explicit wait as shown above. Finally, depending on how you are creating this iframe, you'd need to ensure that your Telegram Data is getting passed to the game when it loads in the iFrame, it might compromise your ability to make a claim, or otherwise expose that your interaction is not coming from within the Telegram Framework.

Thanks,  
Phil

**Comment by Jelingam** [comment]
at first, i think switch_iframe open a new tab and go to iframe src link. something like right pic i mentioned

there is any way we can have only iframe screenshot ? without telegram chat ?

can you check pocketfi all step screenshots ? all screenshots are the same.

**Comment by Jelingam** [comment]
i want to add OpenCV library to this project.
the question is why we need opencv in this project?
as you are aware, seed game are not claim daily bonus, i check every xpath and possibility, but it's not working at the end.

so one way to solve this is using computer vision to detect and recognize the specific part of picture and send this to driver to click on it.
what i need is a clean and fresh screenshot from iframe in every steps.
screenshot with from iframe white background.

one solution is to detect and crop iframe from chromedriver screenshot, but ii'm not sure that is the best solution. reasonable solution is opening iframe source link in empty tab.

**Comment by Jelingam** [comment]
* screenshot from iframe with white background.

**Comment by Jelingam** [comment]
> i want to add OpenCV library to this project. the question is why we need opencv in this project? as you are aware, seed game are not claim daily bonus, i check every xpath and possibility, but it's not working at the end.
> 
> so one way to solve this is using computer vision to detect and recognize the specific part of picture and send this to driver to click on it. what i need is a clean and fresh screenshot from iframe in every steps. screenshot with from iframe white background.
> 
> one solution is to detect and crop iframe from chromedriver screenshot, but ii'm not sure that is the best solution. reasonable solution is opening iframe source link in empty tab.

excuse me for my bad english
correction : 
screenshot from iframe with white background.

**Comment by Jelingam** [comment]
another example:
on SimpleTap game: i check every xpath and it's perfectly fine, but it can not start farming.
to solve this problem, i add opencv library to this game and it is start farming without any problem.
i will Pull Request final code here as soon as it finished

**Comment by thebrumby** [comment]
> another example: on SimpleTap game: i check every xpath and it's perfectly fine, but it can not start farming. 

Are you using the latest code? (simpletap.py) I updated the xpaths on SimpleTap to fix the claim/mining a few days ago.

**Comment by thebrumby** [comment]
> as you are aware, seed game are not claim daily bonus, i check every xpath and possibility, but it's not working at the end.

Ah yeah, prior to the TG updates they utilized the iframe footer, which they aren't doing now. I've fixed the Daily Reward claim in my local code and will push it to the repository after a short testing period.
