### ISSUE TITLE
Help Me: just simple question 

### ISSUE THREAD

**Issue by ashim175** [thebrumby/HotWalletClaimer#227]
i ran my blum script in cmd promt ( windows using docker) and exited the cmd promt but not docker , so will my script run automatically? or do i have to run that 1st session cmd promt in background ?

**Comment by thebrumby** [comment]
Hi,

Docker Desktop provides the Docker engine and will need to be running all the time to make continuous claims. Once your account(s) have been set up as a PM2 session (after the initial setup), the command window can be closed and claims will continue to run provided you have Docker Desktop open (minimized is fine). 

If you shut the PC down overnight etc, if you open Docker Desktop on Windows startup, the claiming should resume automatically without needing to open a CMD window. 

Hope this helps.

**Comment by ashim175** [comment]
this is hamster kombat. 
I don't understand plz look at the pic .
![IMG_20240915_125750_899](https://github.com/user-attachments/assets/a84e86b2-cee5-43dd-bd5d-1637e1013ad7)
![IMG_20240915_125749_381](https://github.com/user-attachments/assets/92f65f11-5292-4573-969c-b76a3441ee0a)

**Comment by ashim175** [comment]
![IMG_20240915_154414_655](https://github.com/user-attachments/assets/e867f752-f04b-4ca1-abf8-226ca5e66fef)
also about this  blum bot (  i already clicked mine button manually). isn't there like play game script?

**Comment by thebrumby** [comment]
Looks to me like you have no connection after switching from the Telegram steps to interacting with the Blum game. The dubug steps can be found here:

https://github.com/thebrumby/HotWalletClaimer/issues/166#issue-2447088307

I'd focus on the section regarding use of the built-in proxy:

## Built-in proxy - needs to be running for Blum, Vertus, and some others!
The built-in proxy is an optional feature for most games, but when enabled, it intercepts data between the browser session and the game. If a user-agent is set and matches an iOS device, the proxy will attempt to rewrite the "tg-data" to show the platform as the iOS app (instead of a desktop browser). Similarly, for Android devices, the data will be modified to indicate it is coming from the Android app.

If the proxy is used and no user-agent is set, it defaults to mimicking an Apple iPhone. Some games, such as Blum, require the use of the proxy to connect, even if it is disabled in the user settings. In such cases, the proxy is automatically enabled for functionality.

If the proxy crashes, you may need to reset it by following these steps:

```
pm2 delete http-proxy
pm2 save
apt install lsof
# or `sudo apt install lsof` if you are on stand-alone Linux and require sudo authority
sudo lsof -i :8080
```

![image](https://github.com/user-attachments/assets/340039b3-0d28-4ede-a6ee-3e079b395148)

If a process is using port 8080, find the process ID (PID) and terminate it. For example, the PID in the above screenshot is 351071, however, you should substitute your real PID for the one in the example. You can kill the process with the following command:

```
taskkill /PID 351071 /F
# or alternatively use `kill` as below. You may also need to use sudo if prompted.  
kill -9 351071
```

After that, restart the built-in proxy:
```
./launch.sh enable-proxy
```

**Comment by thebrumby** [comment]
>  also about this blum bot ( i already clicked mine button manually). isn't there like play game script?

If you hadn't deleted the template when raising the issue and followed the self-help guide, you would already know this :)

**Comment by ashim175** [comment]
thanks ( although i didn't understood 😅)
thank you for the script.

**Comment by ashim175** [comment]
also about hot bot ,it seems we have to manually write the 12 seed phase because I couldn't copy paste in cmd promt ( after inside the root cmd it seems we can't copy paste anything) so it's kinda ..

**Comment by thebrumby** [comment]
No problem :)

So to break it down 

1 - in general, if you need to find out why it's not working for you enabling verbose 3 and debugging screenshots will help you see what's happening within the process
2 - With Blum, considering the Telegram steps are successful, it's almost certainly the proxy. Following the steps to stop and reinstall it might help, pay extra attention when it restarts for any errors.

**Comment by thebrumby** [comment]
> also about hot bot ,it seems we have to manually write the 12 seed phase because I couldn't copy paste in cmd promt ( after inside the root cmd it seems we can't copy paste anything) so it's kinda ..

There's nothing in the script that prevents copy & paste, it depends on what software you are using on how to copy/paste. In web-based Shell-NGN, ctrl+v will paste. In PuTTy, it's a right-click. You can unhide your input in settings if you want to visually see that the copy/paste was successful.

**Comment by ashim175** [comment]
and sir about that gamee bot , i see hammer 🔨 sign does that mean it isn't
working?

**Comment by thebrumby** [comment]
Originally Gamee closed the mining phase, however now it's opened. They seem to have a lot of lag in the interface today, but I think it works with the mining part of the script. 

As documented elsewhere, this system is not compatible with fast-moving objects, so it can't play the racing game, Blum's drop game etc.

**Comment by ashim175** [comment]
1.also about the blum and hot  still don't understand like i have enabled
proxy but when i tried to  , i got  error like timeout and such

**Comment by ashim175** [comment]
it seems deleting whole session and again logged in using new qr worked .

**Comment by ashim175** [comment]
![IMG_20240915_223332_775](https://github.com/user-attachments/assets/c42e72bc-1507-4858-b240-316759574525)
um sir?
also it says debugging costs subscription.

**Comment by ashim175** [comment]
![Screenshot_20240915_225659](https://github.com/user-attachments/assets/8f2489d3-2cd7-4881-85ef-cfcecf626ff5)
does this mean the script is running? 
because 1st time it was giving me update about how much time was remaining till claim like here :
![Screenshot_20240915_225959](https://github.com/user-attachments/assets/b0e87465-01f0-4117-b7c1-6de52b77b1f0)
but i got some bug and had to restart docker , then now my telegram doesn't give me that update.🙂

**Comment by ashim175** [comment]
![Screenshot_20240915_231228](https://github.com/user-attachments/assets/7555420a-bed7-4ea6-afea-b8ae2137f967)
as you can see i only got blum update( after i restarted the docker I deleted and create new session for blum only ). so I don't know if all bots are working.

also how to restart:(

**Comment by thebrumby** [comment]
This should start all instances of `Pocketfi`:
```
/restart Pocketfi:
```
This should restart all games where the wallet name was set to `rising`:
```
/restart rising
```

**Comment by ashim175** [comment]
well🙂 , also why i have to restart this , i mean won't it happen
automatically like after pc/docker gets restart.
also it says no matching found ... )blum is working fine.)

**Comment by ashim175** [comment]
![Screenshot_20240916_090423](https://github.com/user-attachments/assets/59f3b40f-eabf-44c7-b4cd-ffcbbeb6dc90)
also i don't wanna delete session again and again login just because of this 😞

**Comment by ashim175** [comment]
![Screenshot_20240916_100045](https://github.com/user-attachments/assets/7e8a583e-2396-43bb-92b7-94921afeb357)
also i told you 
![Screenshot_20240916_100101](https://github.com/user-attachments/assets/1cd2e7c6-2de8-48fe-9619-3b37890fa786)
that blum rising session was running and after my pc restart ,it was still working but says as you can see in screenshot x time-out not found " , yesterday it was working smoothly, also you can see the rising  blum game , the script didn't claimed 

( SORRY IF YOU FEELING CONFUSING,I TRIED MY BEST TO EXPLAIN 🙂)

**Comment by thebrumby** [comment]
Hi, 

Yesterday a lot of Telegram mini-apps had lag, I have no idea if this was a coincidence or a Telegram issue. The scripts are working fine for me today, if you still have issues, you need to follow the troubleshooting guide to find out where your problem is or to reset the sessions:

https://github.com/thebrumby/HotWalletClaimer/issues/166

**Comment by ashim175** [comment]
i already sent screenshot I can't reset the session, also

..
next,
my script was working fine and telegram vot was gving me all the updates of current running sessions but after i restarted my docker , the bot didn't gave me any update ( docker is still running) and also script wasn't working like it didn't do claim nor nothing,
then when i tried to remake session like for hot ,  it doesn't work,  says " timeout and such " to fix that i have to delete all session and relogin and make new session for all 
help.  :)
