### ISSUE TITLE
Feature Request: Change pm2 behavior

### ISSUE THREAD

**Issue by Jelingam** [thebrumby/HotWalletClaimer#237]
hi @thebrumby 
we can describe the big picture of this project to the concept of **soft sleep** and **hard sleep**
soft sleep occurs when all sessions are occupied, the process goes to sleep for 5 to 15 seconds and come back to check there is an empty session to use for claiming process.
hard sleep occurs when **full_claim** process was done. hard sleep time is based on game next claim.
for short :
soft sleep = [5 - 15] sec
hard sleep = [5 - inf] min

* when a process goes to hard sleep, it consumes about 50 MB of ram.
* every running session consume about 50% of a core of cpu. ( i used maxSessions = 4 and have 2 core cpu server with 8GB of ram, when all sessions are running together, cpu usage goes to max).

because of this two issue, this project can't run on cheaper server with lots of game. a cheap server have 1 cpu core and and 1GB of ram.
the issue i want to address here is maybe there is a new way that we can use to vanish this ram usage when process goes to hard sleep and reduce competition between process to get a free session when all are occupied.

first of all i search for using pm2 capability for this (i'm not expert in this)
my idea for hard sleep is: when full_claim process was done, set a schedule in pm2 to restart this process with cron_tab pattern and after that, process must be shutdown to not using any ram space.

for soft sleep we can use use a parental process that start games sessions one by one, in this way there is no competition between process to get a free session

you can check this keyword on [this link](https://pm2.keymetrics.io/docs/usage/application-declaration/) and see there are applicable or not:
* max_memory_restart
* cron_restart
* Graceful start (i think this feature need a parental control process to decide which game process must be started)
* kill_timeout ( i think this was already used in this project: in manage session if a session exceeds 5 min of running, it will be removed from active sessions)
* shutdown_with_message

for crontab pattern see [this link](https://crontab.guru/every-5-minutes)

second idea is using this parental idea to manage both soft sleep and hard sleep. this idea make less change in current code. a python code named **parent.py** was running at first ( i think it must set in ecosystem.config.js). this **parent.py** start one game process and check system ram and cpu usage and decide whether start a new session or wait to running session goes to hard sleep. when a full claim process for a game was done, it return wait time to **parent.py**, and save this wait time in a txt file, something like **status.txt** your are done in manage session. after save next wait time for running session, **parent.py** stop this process in pm2.
this idea have an another benefit. in current code if you shutdown your server, after starting again, pm2 run all process again.
for example my HOT next claim is 24hr later, if i restart the server after 10hr, process of full claim was restarted and open a new session and find out there is 14hr to next claim. with this idea when server was started again, **parent.py** check txt file and if next time claim was passed, send this game to the queue, and if it was not reached that time, set a new schedule for restart full_claim process.

**Comment by Jelingam** [comment]
you can assume there is a queue for managing process. 
**parent.py** control this queue.
if any game claim next time was passed, it must added to this queue and when full_claim process was done, it must removed from this queue.

benefits:
1. there is no competition for get a free session -> reduce ram usage before start session
2. **parent.py** decide how many session must run simultaneously -> control cpu usage (or we can set max cpu usage is setting)
3. stop the process when it goes to hard sleep -> reduce ram usage when process is in hard sleep

**Comment by thebrumby** [comment]
Hey,

Thanks for taking the time to write this detailed suggestion.

To clarify the current state regarding your soft/hard sleep idea:

Currently, there are two states in the project—**waiting (idle)** and **claiming**. When a game session, as managed by PM2, is waiting for its next claim, the program uses `time.sleep(this_wait * 60)` in the `run(self)` function. If the game session is waiting for a free slot to avoid overloading CPU/RAM limitations, it uses `time.sleep(random.randint(5, 15))` in the `manage_session(self)` function.

So, in the current code, there is no RAM difference and only minimal CPU overhead between what you term as soft and hard sleeps. However, during the "soft" sleep, when a session is queuing because another one is claiming, you'll see a major jump in CPU and memory usage, as the **claiming** script will have launched an instance of ChromeDriver and either Chrome or Chromium browser. The browser can easily consume **400 MB of memory**.

You mention a server with specs of **1GB RAM** and **1 core**, and that it's not able to handle a high number of game sessions using this method. This is correct. Unlike other scripts that need to extract your authentication token for a game and then just make API calls to the game's endpoint, this script uses **Selenium** to control a virtual browser session and step by step follows the same series of clicks and page changes as a human would. I'm proud to say no one has ever reported getting banned for using this method, which I think would be very hard to differentiate from a human user. Unfortunately, using this method, it can easily take **5 minutes** to make a claim.

I don't see a better way of using PM2 so that the RAM overhead disappears and only returns when the script resumes from sleeping. What you're suggesting is a completely new way of handling it, with a single parent script managing a queue to launch the games, which will feed back the time until the next claim to the parent. However, due to occasional errors in the code or games being offline, scripts can get stuck in a loop. PM2, being a production-grade process manager, handles restarts and monitors the number of restarts. If we were to code our own `parent.py` script, we'd need to detect crashes, decide whether to stop processing other claims until this one succeeded, or put it back in the queue, etc. While your idea sounds good in theory, the potential pitfalls and unintended consequences might be significant.

I think at best, on a **1 core 1 GB RAM** server, you might just be able to handle **2 concurrent claims**, so you could increase the number of sessions by 12. But ultimately, a user with this level of server couldn't run a significantly higher number of processes.

I provided this project and maintain it free of charge. If someone else wants to fork it or contribute their work back to the project, they are welcome to do so. However, committing a significant amount of time to refactor all the code for this purpose isn't feasible for me at the moment.

I appreciate your understanding, and thank you again for your suggestion. If you or anyone else is interested in implementing these changes, I'd be happy to review any pull requests.

Best regards,

**Comment by Jelingam** [comment]
thank you for your effort and your attention
next week i wrote this parent.py for whom was intended to this idea, and pull it here

**Comment by Jelingam** [comment]
> I think at best, on a 1 core 1 GB RAM server, you might just be able to handle 2 concurrent claims, so you could increase the number of sessions by 12. But ultimately, a user with this level of server couldn't run a significantly higher number of processes.

if run one process at a time (maxSessions=1) and only this process consume ram (not in current code), i think this can be run on 1cpu , 1GB ram server

**Comment by thebrumby** [comment]
Currently, if you use a 1 GB server, I think you can run a total of about 7 or 8 sessions with one active claim before it runs out of memory.
