### ISSUE TITLE
Help Me: About update 

### ISSUE THREAD

**Issue by Keyz400** [thebrumby/HotWalletClaimer#262]
When you do some changes/update in your repo. Will my code automatically get updated in VPS. 
OR
If I have to do it manually, after updating (pull) I have to restart that game (in game where you made changes, e.g. i am already running the game "Blum" and  have you made some changes in "Blum" , so i have to stop it and need to restart again to get the new changes?)

**Comment by thebrumby** [comment]
Hi, 

It depends on how your system is configured.

- Docker: Automatically pulls updates every 12 hours (provided the daily update process is running).
- Standalone: pulls updates **only** when the **user** executes `git pull`  in the `HotWalletBot` directory.

When the script creates a new PM process, it sets this flag: `--watch {script_path}`

This means the script will automatically restart when the latest code is pulled. However, if you've started and stopped the scripts manually, you would need to check if the watching flag is still set. It's the right hand column of the image below:

```
pm2 list
```

<img width="719" alt="image" src="https://github.com/user-attachments/assets/410720af-d80d-45fb-9343-955751254467">

As you can see, all mine are disabled from auto-restarting, mainly because I just migrated from a different server.

**Comment by Keyz400** [comment]
> Hi,
> 
> It depends on how your system is configured.
> 
> * Docker: Automatically pulls updates every 12 hours (provided the daily update process is running).
> * Standalone: pulls updates **only** when the **user** executes `git pull`  in the `HotWalletBot` directory.
> 
> When the script creates a new PM process, it sets this flag: `--watch {script_path}`
> 
> This means the script will automatically restart when the latest code is pulled. However, if you've started and stopped the scripts manually, you would need to check if the watching flag is still set. It's the right hand column of the image below:
> 
> ```
> pm2 list
> ```
> 
> <img alt="image" width="719" src="https://private-user-images.githubusercontent.com/29182343/376050191-410720af-d80d-45fb-9343-955751254467.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTczOTMsIm5iZiI6MTcyODg5NzA5MywicGF0aCI6Ii8yOTE4MjM0My8zNzYwNTAxOTEtNDEwNzIwYWYtZDgwZC00NWZiLTkzNDMtOTU1NzUxMjU0NDY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA5MTEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZmExZTYyYjk3M2ZjYmEwZmRlZjk3ZjMxYWNjMjBjNzhhZmE5ZTk2MzQwMjU1MDgwNmNhYzViZWI3MzNjZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.C-zNwh6vQF8MUOs8sToT9HOSUZ3PLaoYPVu7qnPolII">
> As you can see, all mine are disabled from auto-restarting, mainly because I just migrated from a different server.

Thank you sir 😊,
For your great help.

Once I started my docker on vps server I no need to do any thing, all updates done automatically? For running games too?

**Comment by thebrumby** [comment]
Hi @Keyz400,

Yes, the default situation is you don't need to do anything on Docker. It will pull updates twice daily and automatically restart the games using the new code.
