### ISSUE TITLE
Help Me:  The wait timer is still showing: Filled.

### ISSUE THREAD

**Issue by BraveCanister** [thebrumby/HotWalletClaimer#270]
<img width="855" alt="image" src="https://github.com/user-attachments/assets/001448f7-d89d-4430-921f-55ce0f11af9a">

I have 0.11 NEAR on my balance for testing purposes. Currently upgraded to fill time of 4 hours, that should give me 35 days of claiming every 4 hours (1 NEAR = 2000 claims), which is more than plenty. Is there a way to change this floor value?

**Comment by thebrumby** [comment]
Hi @BraveCanister,

You are right, it would be enough for 35 days if the HOT developers didn't have a lower limit in place for gas fees. Part of the game mechanics is that you can make **gas-free** claims and receive 50% fewer HOT tokens if you carry out various tasks like watching YouTube videos etc; as the HOT devs then get an income from the YouTube creator program to cover the costs.

Unfortunately, it does not matter what I set the floor to, it's the game developers who are rejecting your claim as the script is not going to watch the video for you and enter the hidden code. The script will always try to make a claim regardless of your Near balance; the message is provided as a courtesy to explain why your claim failed.

**Comment by BraveCanister** [comment]
I see. What about the cases when I have "warmed up" the account already, including watching the video? Past that point it continues to claim just fine with a balance of 0.1 NEAR.

**Comment by thebrumby** [comment]
The game devs intermittently let claims through below 0.2 Near, so if you’re happy with that then fine. If you want to avoid then rejecting your claims due to low Near balance, it would be better to top up. 

Of the 21 games that are currently working with this script, 3 are mined directly on chain and require gas fees:
- Hot on Near Protocol
- Cold on BNB
- Ocean/wave on SUI

The rest don’t go directly to chain and don’t require gas fee  for every claim.

**Comment by thebrumby** [comment]
> Just checked, pretty confident it does not reduce the claim to 50% if the balance is below 0.2 NEAR (it should only occur when a special pop-up window shows up offering to top up or reduce the mining reward once the gas-free claims are exhausted).
