### ISSUE TITLE
"Kindly check in the GUI if you can claim manually, and consider topping up" but balance is way over 0.2 NEAR

### ISSUE THREAD

**Issue by BraveCanister** [thebrumby/HotWalletClaimer#275]
I have over 0.2 NEAR and the script was claiming fine just a while ago, but tonight's market dip drew the price down by 10% and the script can't claim certain profiles anymore? You mentioned earlier the ability to claim is not tied to the balance equivalent in USD but it doesn't seem to be this way. 

![image](https://github.com/user-attachments/assets/eef8818d-dcb8-4145-b6f3-1e67cdf34c2e)
![image](https://github.com/user-attachments/assets/edfc8044-88fb-4555-b55f-904188743be0)

**Comment by thebrumby** [comment]
Hi,

The claim function of this script does not consider your account's NEAR balance when making a claim. It will attempt to claim every time the pot is full (plus/minus your offset, if any). From time to time, the HOT game devs set additional requirements if your balance is low, usually to monetize the user's action (e.g., watch a YouTube video, subscribe to a channel, etc.).

The other day, I had three accounts drop below 0.25 NEAR, and the claim failed on all of them because of these extra steps. However, my other 20+ accounts with higher balances continued to claim without issue. I topped up the affected accounts, and after restarting the script, all three successfully claimed on the first attempt.

Unfortunately, here are your options:

1. **Top up the NEAR balance** of the affected accounts.
2. Since you have five affected accounts, **transfer the NEAR from one or two other accounts** so at least one account has >0.25 NEAR, then test if it claims.
3. **Wait until the HOT devs change the criteria** to allow claims with a lower NEAR balance.

Hope this helps clarify things!

**Comment by bscongluanbui** [comment]
> Hi,
> 
> The claim function of this script does not consider your account's NEAR balance when making a claim. It will attempt to claim every time the pot is full (plus/minus your offset, if any). From time to time, the HOT game devs set additional requirements if your balance is low, usually to monetize the user's action (e.g., watch a YouTube video, subscribe to a channel, etc.).
> 
> The other day, I had three accounts drop below 0.25 NEAR, and the claim failed on all of them because of these extra steps. However, my other 20+ accounts with higher balances continued to claim without issue. I topped up the affected accounts, and after restarting the script, all three successfully claimed on the first attempt.
> 
> Unfortunately, here are your options:
> 
> 1. **Top up the NEAR balance** of the affected accounts.
> 2. Since you have five affected accounts, **transfer the NEAR from one or two other accounts** so at least one account has >0.25 NEAR, then test if it claims.
> 3. **Wait until the HOT devs change the criteria** to allow claims with a lower NEAR balance.
> 
> Hope this helps clarify things!

Hi admin. I answer the question of video missions. But when claim with low near (I have abou 0.2near/account) they still show question. I relized that I click the mission and back to claim, It's not show anymore. That maybe lag in game.
So it will be good if you add more step to click the mission and then claim again. Because if I have alot of accounts, top up 0.25 near is a big money, and who know in the future, dev will increase the balance to avoid the video?

**Comment by thebrumby** [comment]
> So it will be good if you add more step to click the mission and then claim again. Because if I have alot of accounts, top up 0.25 near is a big money, and who know in the future, dev will increase the balance to avoid the video?

I've noticed three different versions of the "low balance" requirement these last few weeks. Given that I don’t personally use this feature, I can't commit to updating the code each time a new variation is introduced.

**Comment by bscongluanbui** [comment]
> > So it will be good if you add more step to click the mission and then claim again. Because if I have alot of accounts, top up 0.25 near is a big money, and who know in the future, dev will increase the balance to avoid the video?
> 
> I've noticed three different versions of the "low balance" requirement these last few weeks. Given that I don’t personally use this feature, I can't commit to updating the code each time a new variation is introduced.

I mean I already answer the question of video but it’s still lag. So if update click on the mission step, will resolves all the problem and variations. Thank you

**Comment by thebrumby** [comment]
OK, next time I run out of gas fee I will look at it. Thanks.

**Comment by thebrumby** [comment]
Hi, 

The system can not interact with the final part to enter the code because of how the game devs handle it. The solution is being able to claim using this python script is to top up the Near, thanks.
