### ISSUE TITLE
is using AWS VPC safe with Telegram?

### ISSUE THREAD

**Issue by BraveCanister** [thebrumby/HotWalletClaimer#277]
I've set up AWS per the video instructions. I will be using residential proxies to set up my session and HOT accounts, but I wonder how Telegram generally reacts to having an account connect from IP associated with Amazon server? Wouldn't that get the authorization token revoked or an account being outright banned?

Previously, I have used datacenter proxies for Telegram and it would result in accounts being logged out of all devices (not banned, but logged out, and since they were accounts made with virtual phone numbers that I have no access to, I automatically lose access), hence my concern.

**Comment by thebrumby** [comment]
Hi,

I previously hosted over ten accounts on AWS, using virtual phone numbers from an online service. I didn’t experience any issues related to the AWS data center itself. Since this project operates within an authentic Google Chrome browser session, keep in mind that if a purchased account revokes its link to your browser session, the script will no longer be able to log in.

One exception to note is with HOT accounts. HOT restricts seed-phrase creation to a single HOT account per Telegram account. However, if you obtain the seed phrase and complete the first claim before access to the account is revoked, you can use those seed-phrase credentials to log in from another account. This method allows you to manage multiple HOT accounts with a single Telegram sign-in.

Hope this helps!
