### ISSUE TITLE
I cannot store the session after successfully logging in using the OTP method

### ISSUE THREAD

**Issue by itcthienkhiem** [thebrumby/HotWalletClaimer#28]
I cannot store the session after successfully logging in using the OTP method.
![image](https://github.com/thebrumby/HotWalletClaimer/assets/2140355/a752b9ff-1eeb-4189-8745-c3d0e8825064)
![image](https://github.com/thebrumby/HotWalletClaimer/assets/2140355/91066287-d9e3-4dac-9d6b-a92005b35091)

Please help me.
Thanks.

**Comment by thebrumby** [comment]
Hi,

Looking at your screenshot, the process is failing because Telegram did not accept the 2FA password. You didn't mention which script you are running, but I tested with HOT on an account that uses Two Factor Authentication and this should be the correct output:

<img width="807" alt="image" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/4cea6a35-9148-4d93-940c-bb7da2e898c2">

From the screenshots you provided, it doesn't show the step why it failed.

Potential solutions include.
1) Log into [https://web.telegram.org ](https://web.telegram.org/) and ensure your 2FA password is correct
2) The script reported that after entering the password, Telegram was still asking you to enter a password:
    - If you already had some failed attempts run `./remove-process.sh`
    - Select option `2` and remove any saved TG account or game accounts (eg HOT:Wallet1) if they didn't work
    - Repeat the log in process with the failed attempts deleted
    - If it fails again, look for the screenshot/HTML dump which include **"final check to make sure we are correctly logged in"** to get more details
    3) Disable 2FA in your Telegram app, log into and save the TG account, re-enable 2FA
    
    Please let us know how you get on
