### ISSUE TITLE
Moving claimer from one PC to another

### ISSUE THREAD

**Issue by BraveCanister** [thebrumby/HotWalletClaimer#295]
I'm trying to move my claimer from one Windows PC to another. I created a compressed tarball, moved it from one PC into another PC's docker usr/src/app, installed nano editor, made the recovery script, but when I run it, I get the following error: 

![image](https://github.com/user-attachments/assets/3520dda8-07cd-4554-9fb4-ae33178f9235)

Not sure where to move from there. 

At the same time these sessions are registered in ./launch.sh status (as inactive)

![asdas](https://github.com/user-attachments/assets/a99378b0-a3aa-4cc9-a868-03ff7a27fba7)

**Comment by thebrumby** [comment]
Hi BraveCanister,

It looks like your `./recover_pm2.sh` script isn't being found when you try to run it. This could be due to a few different reasons. Here's a quick checklist to help troubleshoot and resolve the issue:

### 1. **Check if the Script Exists**
First, make sure the script is actually present in the expected location by using the `ls` command:

```bash
ls -l /usr/src/app/recover_pm2.sh
```

### 2. ***Check Script Permissions***
The script might not have executable permissions. To make it executable, use:
```
chmod +x /usr/src/app/recover_pm2.sh
```
After that, try running the script again with:
```
./recover_pm2.sh
```
