### ISSUE TITLE
Docker for arm not update the newest feature

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#31]
I'm using docker on aarch64 device and it doesnt had the latest version. PLS update this. 
Best regards

**Comment by thebrumby** [comment]
Hi,

Which newest feature? Oxygen?

Games are updated independently of the docker build and are pulled for Git twice daily.

If you wish to take immediate advantage you can run `./pull-games.sh` manually.

**Comment by bscongluanbui** [comment]
No my Friend, It's lack of game like seed, Blum. I tried to run /pull-games.sh but still not update

**Comment by thebrumby** [comment]
OK, I will test :)

**Comment by bscongluanbui** [comment]
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[PM2] Resurrecting
[PM2] Restoring processes located in /root/.pm2/dump.pm2
[PM2][ERROR] Failed to read dump file in /root/.pm2/dump.pm2
[PM2] Restoring processes located in /root/.pm2/dump.pm2.bak
[PM2][ERROR] Failed to read dump file in /root/.pm2/dump.pm2.bak
[PM2][ERROR] No processes saved; DUMP file doesn't exist
┌────┬───────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name      │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
└────┴───────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
(node:25) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/app pulling latest changes.
fatal: unable to access 'https://github.com/thebrumby/HotWalletClaimer.git/': Could not resolve host: github.com
cold.py is already up-to-date.
hot.py is already up-to-date.
tree.py is already up-to-date.
vertus.py is already up-to-date.
wave.py is already up-to-date.
Script executed at: Thu May 30 12:50:19 UTC 2024
I got this log in docker

**Comment by thebrumby** [comment]
Hi :)

It says that your docker container can't resolve github.com. Do the existing games work? Or they fail to log in also?

**Comment by bscongluanbui** [comment]
> ./pull-games.sh
in docker it fail. But when I use normal script It's working

**Comment by thebrumby** [comment]
Hi,

It sounds like you're facing a tricky network connectivity issue with your Docker container. There could be several reasons for this, including DNS misconfigurations, network isolation, or firewall rules that might be blocking access to GitHub. 

Since you mentioned that access to Telegram Web is working to play the games, it's curious that GitHub specifically is inaccessible. This suggests that the issue might be more related to DNS resolution or specific network routes blocking GitHub.

Regarding the manual steps you tried with `git clone`:

```
git clone https://github.com/thebrumby/HotWalletBot.git updated_scripts
cp updated_scripts/games/oxygen.py games/
```

If these commands also failed, it reinforces the idea that there’s a network or DNS issue specific to GitHub connectivity.

It's important to ensure consistent updates, especially when frequent changes are needed, like with game developments. Manually pushing updates isn't feasible, as you noted, so having a reliable way for the container to pull updates directly from GitHub is crucial.

From the command line (not inside docker) you can try to contact Google and GitHub to see if you have standard web ports open:

```
ping -c 4 google.com
```
```
ping -c 4 github.com
```

Here are a few steps you can take to troubleshoot this issue further:
1. Check the DNS settings in your Docker container from the CLI (`docker exec -it telegram-claim-bot  cat /etc/resolv.conf`).
2. Ensure that no firewall rules are specifically blocking GitHub access.
3. If using a proxy, verify that the Docker container has the correct proxy configuration set.

The connection to GitHub is working well from from all my test environments including Amazon Web Services and Contabo VPS, as well as locally. This might indicate that the issue could be specific to how your Docker network is configured or isolated in the environment where the issue occurs.

**Comment by thebrumby** [comment]
If you have connection outside the Docker container but not inside you can install ping and try inside the container:

```
apt install iputils-ping
ping -c 4 github.com
```

**Comment by bscongluanbui** [comment]
> ```
> cp updated_scripts/games/oxygen.py games/
> ```

Thank you. The problem is about DNS. thanks for your support

**Comment by thebrumby** [comment]
@bscongluanbui,

Can you remember how you resolved the DNS issue? A user from India has the same problem here. 

Thanks

**Comment by bscongluanbui** [comment]
> @bscongluanbui,
> 
> Can you remember how you resolved the DNS issue? A user from India has the same problem here.
> 
> Thanks

Hi I install docker with comment 
docker run -d -t --name bot --dns="1.1.1.1" --restart unless-stopped thebrumby/telegram-claim-bot:latest

**Comment by thebrumby** [comment]
Fantastic, I'll relay that to our other user.
