### ISSUE TITLE
Hexacore Claim passive mode

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#37]
HI the Hexacore game do not auto claim rewards (about 12h). Can you add this in the future

**Comment by thebrumby** [comment]
Hi,

The box is set to claim if available when the Hexagon is ready for clicking. In general, we do not intend to support any side missions, as they introduce additional steps that can go wrong. Each time the game developer changes the format, we have to revisit the game to remap the clicks.

However, since we have already added the function to click the lucky box for this one, we will amend the timing mechanism and upload it. :)
