### ISSUE TITLE
Have you tried multiple accounts using 1 telegram account?

### ISSUE THREAD

**Issue by Wapweb** [thebrumby/HotWalletClaimer#4]
Hey there)
Have you tried multiple accounts using 1 telegram account? Have you checked if telegram user id is transferred to HERE backend? (in this case they could ban account if they see one tg uses multiple accounts)

**Comment by thebrumby** [comment]
Hi! Each claim session operates independently with its own set of cookies: Telegram cookies specifically for web.telegram.org, and game cookies under tgapp.herewallet.app. Consequently, I'm able to run 5 to 6 game sessions per single Telegram login. Regarding data sharing, to the best of my knowledge, Telegram only relays IP addresses and other basic information to HereWallet, as indicated in their notification pop-ups. I haven’t delved deeply into the specifics of what the API transmits.

As for the potential of being banned, it presents an interesting scenario since your rewards are mined directly onto the Near Protocol Blockchain, as can be seen on the blockchain explorer. To my knowledge, there aren't any Terms and Conditions tied to the usage of the HereWallet app, or at least nothing explicitly agreed upon during the signup process.

**Comment by thebrumby** [comment]
Based on your question, I have updated the readme documentation:

💡 **TIP:** While you cannot register more than one wallet to a single Telegram username, this script enables you to manage multiple pre-existing HereWallet accounts using just one Telegram account by initiating multiple individual sessions. For straightforward setup, consider using **SCREEN** (refer to the quick start guide below). For more advanced users, [PM2](#pm2) is recommended.

**Comment by Wapweb** [comment]
Thanks!

**Comment by thebrumby** [comment]
Always a pleasure, and a great question by the way.

P.S. Feel free to update to the new version, it's running about 30 seconds per claim faster than the last version, and is more stable in making claims :)

**Comment by thebrumby** [comment]
I have 14 accounts running on the same server, and have the setting to allow 4 simultaneous claims at once. I forced PM2 to restart them all to watch the log go crazy initializing them all again.

**Comment by Wapweb** [comment]
> I have 14 accounts running on the same server, and have the setting to allow 4 simultaneous claims at once. I forced PM2 to restart them all to watch the log go crazy initializing them all again.

Wow, not bad at all)
