### ISSUE TITLE
Blum: daily rewards

### ISSUE THREAD

**Issue by fly-a1one** [thebrumby/HotWalletClaimer#45]
Does this script collect daily rewards in Blum that appear on the full screen of the app every day? For example, if I leave the script running for a few days

P.S. I'm sorry for the possible offtop, but I didn't know where else to ask a question. I will be very grateful for the answer

**Comment by thebrumby** [comment]
Hi, 

Thanks for the comment. At the minute it does not, but mainly because when we first added the game, it didn't have a daily claim.

However, it seems logical for us to claim that, and we might even need to clear it for the rest of the script sequence to execute correctly. So, we will monitor our test accounts in the coming days, and update the code, and yourself, as we find more.

If you get a chance to include a screenshot, please do so, to ensure we're talking about the same thing. 

Kind regards.

**Comment by fly-a1one** [comment]
Yes, I think we understood each other. Just in case, I attached a screenshot (it's old, but the meaning doesn't seem to have changed)
![photo_2024-06-12_20-55-45](https://github.com/thebrumby/HotWalletClaimer/assets/70477273/a7764dab-7b8c-463c-aa1b-8fe317f46c94)

**Comment by thebrumby** [comment]
Great, so the reward is passive, i.e., you get it regardless of clicking the "Continue" button or not, but we may need to clear it, and can possibly scrape and grab the number of days to show in the status.

Thanks :)
