### ISSUE TITLE
Bulk process addition function pm2

### ISSUE THREAD

**Issue by goncharovnr** [thebrumby/HotWalletClaimer#53]
![image](https://github.com/thebrumby/HotWalletClaimer/assets/97805496/ec52d883-c908-4275-9878-3221c07c012d)
Hello, would you like to make a function so that when you select a TG session to create a pm2 process, you can select all sessions at once so that the script creates processes for all sessions at once (attached an example)

**Comment by thebrumby** [comment]
Hi,

It would require more than just a simple for-each loop, as it would need some checks if the folders already exist (whether to overwrite or keep the existing) and what happens if it already exists in PM2 etc. Overall it's an OK idea, but in reality, I don't have half a day or so to write, test and backfit it to the 8 scripts, so for now we won't be actioning it. 

Thanks.
