### ISSUE TITLE
Discussion: Should we add any other projects?

### ISSUE THREAD

**Issue by Sergey26Tarasenko** [thebrumby/HotWalletClaimer#7]
Hello. Thank you for the amazing project which works 😃 

Can I use this project for adapting to any telegram project? example for Blum, Vertus ...?

Maybe you have plans for adapting to any telegram projects?

**Comment by thebrumby** [comment]
Hey Sergey,

My initial thought was that I didn't want to add more projects,  because in this first month, of the 5,000,000+ HOT users, only 10 per day download the script, and the project only has 12 stars, so while it is working, I'm not sure if it's helping that many people or not. 

However, the core functions of the script work well and I'm familiar with how to modify it. So an open question to anyone, please tell me more about which projects you'd like to see. How many users? What makes them a good candidate to add to this system? And then maybe we'll pick one for this next week and try to integrate it!

Thanks for the suggestion :)

**Comment by Sergey26Tarasenko** [comment]
I see several projects that may be relevant. Blum, Vertus. Also I have other projects, but not sure that you will interesting.

Why you write script on python? If there are any restrictions if you write in js?

Thanks!

**Comment by thebrumby** [comment]
I just like the flow of Python compared to JS, that's the main reason I use it.

**Comment by Sergey26Tarasenko** [comment]
> Hey Sergey,
> 
> Blum looks to be closed to new registrations for now. However, I added Vertus and a couple of others!
> 
> Happy Claiming!

Hello, for Blum you can use this ref link - t.me/BlumCryptoBot/app?startapp=ref_XX7V6NwrPo
I added my version of bots. I use js, puppeteer, pm2 and I happy. Thanks a lot for idea.

**Comment by thebrumby** [comment]
Great to hear you have everything working well in JS! I'll try the link you sent later in this week :)
