### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by maksim44m** [thebrumby/HotWalletClaimer#80]
Can you tell me how to add a login and password to the proxy? I've already tried all the options and every time "Proxy disabled in settings", although the proxy settings are enabled

**Comment by thebrumby** [comment]
Hi, 

You can't add a password and username to the proxy using the unmodified script, we spent a lot of time looking at how to make a command line Chrome extension but parked it due to the time it was taking. 

Some games will not work with the built-in proxy and force it off - Hexacore is one, I think there's also one other. 

I hope that helps.
