### ISSUE TITLE
Cold

### ISSUE THREAD

**Issue by Dumpff** [thebrumby/HotWalletClaimer#88]
Cold don't work
```CHROME DRIVER INITIALISED: Try not to exit the script before it detaches.
Step 01 - Backup restored successfully.
Step 02 - Attempting to check for the start button (should not be present)...
Step 03 - Attempting to open a link for the app...
Step 04 - Attempting to click the 'Launch' button (probably not present)...
Step 05 - Attempting to switch to the app's iFrame...
Step 07 - Attempting to find log-in button (may not be present)...
Step 07 - An error occurred: Message: javascript error: Cannot read properties of null (reading 'click')
  (Session info: chrome-headless-shell=126.0.6478.114)
Stacktrace:
#0 0x56014130869a <unknown>
#1 0x560140feb0dc <unknown>
#2 0x560140ff07e9 <unknown>
#3 0x560140ff285c <unknown>
#4 0x56014107a5a9 <unknown>
#5 0x56014105a872 <unknown>
#6 0x5601410795c3 <unknown>
#7 0x56014105a613 <unknown>
#8 0x56014102a4f7 <unknown>
#9 0x56014102ae4e <unknown>
#10 0x5601412ce86b <unknown>
#11 0x5601412d2911 <unknown>
#12 0x5601412ba35e <unknown>
#13 0x5601412d3472 <unknown>
#14 0x56014129ecbf <unknown>
#15 0x5601412f8098 <unknown>
#16 0x5601412f8270 <unknown>
#17 0x5601413077cc <unknown>
#18 0x7fa0a42cea94 <unknown>
#19 0x7fa0a435bc3c <unknown>


CHROME DRIVER DETACHED: It is now safe to exit the script.```

**Comment by Wellynounet** [comment]
hello,  Maybe try with proxi enable 
i dont have any issue on cold cant help you

**Comment by Dumpff** [comment]
But I don't have a proxy and there is no point in buying it to try the game on 2 accounts. I think that if the game works, it should launch without a proxy.

**Comment by Wellynounet** [comment]
same answer :)

**Comment by thebrumby** [comment]
Hi @Dumpff,

The game works fine without a proxy, there's no need to buy anything. `Message: javascript error: Cannot read properties of null (reading 'click')` means the element the script wants to interact with is not there after it restores your saved game session.

If you want to debug the issue, you'd have to edit settings, turn on debug, and set verbose to level 3. You should then look in your screenshots directory, and the sub-directory for the game to see what's happening. The script can fail for many reasons, such as:

1) You're TG session became logged out.
2) You were searching for something in the TG GUI and it got captured.
3) Something corrupted your "conversation" with the game bot

Etc, only the screenshots extra verbose messages will show where the problem is.
