### ISSUE TITLE
telegram session get logged out and can't login again

### ISSUE THREAD

**Issue by bangbangbong** [thebrumby/HotWalletClaimer#92]
Some of my Telegram sessions keep logging out, and currently, I'm unable to log in again using the bot. I've tried logging in via web Telegram, and it works fine. However, when attempting to log in with the bot, I consistently receive the message: '2FA password entry is still showing, check your debug screenshots for further information.' The weird thing is, the session appears as an active session (successful login) on my Telegram app.
![cant login](https://github.com/thebrumby/HotWalletClaimer/assets/162609910/85292cba-9f18-44e2-8800-e346e7cdded4)

**Comment by thebrumby** [comment]
Hi @bangbangbong,

As the text suggests, you need to enable debugging in the settings and check your screenshots. 

I just tested my 2FA account and the script is working well. 

Thanks

**Comment by thebrumby** [comment]
Hi,

The debugging screenshots are taken by the browser driver and show what's happening in the browser. They are located in ./HotWalletBot/screenshots/ and then in the folder named after the wallet you are struggling with. The image you attached is a screenshot of the script running and is not part of the debugging screenshots.

The debugging screenshots will look something like this:

![image](https://github.com/thebrumby/HotWalletClaimer/assets/29182343/b14abf18-32b1-41b2-8790-d57a74891e6a)

Also, I'm curious about what differences you might have found regarding the def test_for_2fa() function that handles accounts with 2FA. While the new code is in a slightly more modern format, as it is now in a separate file for core functionality rather than in each individual game file, the underlying code has not been changed for months.

Thanks
